add_newline = false
scan_timeout = 10
[character]
success_symbol = "[➜](bold green)"
error_symbol = "[✗](bold red)"
vicmd_symbol ="[←](bold blue)"
# success_symbol = "[❯](bold green)"
# error_symbol = "[✗](bold red)"
# vicmd_symbol ="[❯](bold blue)"
# success_symbol = "[»](bold green)"
# error_symbol = "[✗](bold red)"
# vicmd_symbol ="[»](bold blue)"
[directory]
truncation_length = 1
truncation_symbol = ""

[package]
disabled = true
